---
title: "Chapter 3: Quantile Regression R plots"
author: "Joseph Ho"
date: "2023-06-06"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Quantile regression for El Nino data
Source of data: El Nino. UCI Machine Learning Repository. 1999. \url{https://doi.org/10.24432/C5WG62}

We use the observations in 1997 (where El-Nino occured) that are cleaned (and omitted observations with missing data).

```{r El-nino data, echo=FALSE}
library(readr)
elnino <- 
  read_csv("./elnino_clean_final_1997.csv") # import cleaned data
#head(elnino) # 14776 observations

# define variables
latitude <- elnino$Latitude
longitude <- elnino$Longitude
zonalwinds <- elnino$Zonal_Winds
meridionalwinds <- elnino$Meridional_Winds
humidity <- elnino$Humidity
airtemp <- elnino$Air_Temp
seasurfacetemp <- elnino$Sea_Surface_Temp
```

```{r El-nino data quantreg, echo=FALSE,results='hide',fig.keep='all'}
# original quantile regression (single covariate)
library(quantreg)
plot(airtemp, seasurfacetemp, main="Linear and median regression of
     El Nino data 1997", cex=0.5)
fit1 <- rq(seasurfacetemp ~ airtemp, tau = 0.5) # median regression
#summary(fit1)
abline(fit1, col="blue") # median regression line (blue solid line)
abline(lm(seasurfacetemp ~ airtemp), lty = 2, col = "red") # linear regression line (red dotted line)
# legend/key
legend("bottomright", legend=c("Median regression", "Linear regression"),
       col=c("blue", "red"), lty=1:2, cex=0.7)


# quantile regression on discrete set of taus
q <- rq(seasurfacetemp ~ airtemp, tau = 1:9/10)
plot(summary(q))
# Reference: https://rpubs.com/ibn_abdullah/rquantile

# Computation takes more time due to more observations
```

```{r El-nino data quantreg quantile functions, echo=FALSE,results='hide',fig.keep='all'}
library(quantreg)
library(viridis)
plot(airtemp, seasurfacetemp, main="Quantile functions of
    El Nino data 1997", cex=0.5)
n <- 10 # number of quantile functions (lines)
for (i in 1:(n-1)){
  elnino_fit_quant <- rq(seasurfacetemp ~ airtemp, tau = i/n)
  abline(elnino_fit_quant, col=viridis(n-1)[i]) # quantile regression line (solid lines)
}
#abline(lm(seasurfacetemp ~ airtemp), lty = 2, col = "red") # linear regression line (red dotted line)
```
From the plot, we see quantile crossing between the upper quantile functions at airtemp=30.

``` {r El-nino data quantreg, echo=FALSE,results='hide',fig.keep='all'}
# original quantile regression (multivariate)
q_mul <- rq(airtemp ~ latitude + longitude + humidity, tau = 5:95/100)
plot(summary(q_mul))

# covariance between the covariates
c(cor(latitude, longitude), cor(latitude, humidity), cor(longitude, humidity))

# Computational time: more
# `non-positive fis` refers to local density estimates made at each x_i value are negative and are set to 0 (when number of these is small compared to sample size, it is harmless) Ref: https://stat.ethz.ch/pipermail/r-help/2009-June/393112.html
```
